language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo run --example hello_world
  - cargo run --example mark
  - cargo run --example thread_range