[package]
name = "nvtx-rs"
version = "0.1.0"
authors = ["Spencer Imbleau <spencer@imbleau.com>"]
edition = "2018"
description = "Rust bindings for NVIDIA® Tools Extension SDK (NVTX)"
homepage = "https://github.com/simbleau/nvtx-rs"
repository = "https://github.com/simbleau/nvtx-rs"
license = "MIT/Apache-2.0"
categories = ["api-bindings"]
readme = "README.md"
exclude = ["assets/*", "examples/*"]

[build-dependencies]
cc = "1.0"